name: update-benchmark-data-action

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

permissions:
  contents: write

jobs:
  update-benchmark-data-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      working-directory: pages
    steps:
      - name: actions-checkout
        uses: actions/checkout@v3

      - name: actions-setup-node
        uses: actions/setup-node@v3
				working-directory: pages
        with:
          node-version: 18
          cache: npm

      - name: npm-install
				working-directory: pages
        run: npm install

      - name: node-run
				working-directory: pages
			  env:
          PAPERTRAIL: ${{ secrets.PAPERTRAIL }}
					GHTOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node ./benchmark-download.js

			- name: git-commit
      	uses: stefanzweifel/git-auto-commit-action@v4
				working-directory: pages
				with:
					commit_message: 'update benchmark data'
			    commit_options: '--no-verify'
			    file_pattern: 'pages/*.json, pages/*.md'
			    status_options: '--untracked-files=no'
			    skip_fetch: true    
			    skip_checkout: true
